version: '3'

services:
  api:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    command: bash -c "
        ./src/manage.py migrate
        && ./src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/:/app/src/
    ports:
      - 8000:8000
    env_file:
      - compose/local/.env
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

volumes:
  pg-data:
