version: '3'

services:
  api:
    build:
      context: .
      dockerfile: compose/prod/Dockerfile
    command: bash -c "
        cd src
        && ./manage.py migrate
        && ./src/manage.py loaddata src/fixtures/initial_tiers.json
        && gunicorn core.wsgi:application -c core/gunicorn.conf.py --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - compose/prod/.env
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

volumes:
  pg-data:
