# Generated by Django 4.0.4 on 2022-05-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_lossless_resolution', models.BooleanField()),
            ],
            options={
                'default_related_name': 'img_storage_tiers',
            },
        ),
        migrations.CreateModel(
            name='ImageResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imgstorage.imageresolution')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imgstorage.accounttier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'images',
            },
        ),
        migrations.AddField(
            model_name='accounttier',
            name='resolutions',
            field=models.ManyToManyField(to='imgstorage.imageresolution'),
        ),
    ]
