# Generated by Django 4.0.4 on 2022-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttier',
            name='allow_expiring_links',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
