# Generated by Django 4.0.4 on 2022-05-19 15:54

from django.db import migrations, models
import imgstorage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imgstorage', '0002_accounttier_allow_expiring_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=imgstorage.models.get_upload_path),
        ),
    ]
