# Generated by Django 4.0.4 on 2022-05-19 16:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import imgstorage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imgstorage', '0003_image_uuid_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(upload_to=imgstorage.models.get_thumbnail_upload_path)),
                ('resolution', models.IntegerField()),
            ],
            options={
                'default_related_name': 'thumbnails',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='accounttier',
            name='resolutions',
        ),
        migrations.AddField(
            model_name='accounttier',
            name='resolutions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='ImageResolution',
        ),
        migrations.AddField(
            model_name='imagethumbnail',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgstorage.image'),
        ),
    ]
