# Generated by Django 4.0.4 on 2022-05-19 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstorage', '0004_imagethumbnail_remove_image_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttier',
            name='resolutions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=6),
        ),
    ]
