# Generated by Django 4.0.4 on 2022-05-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstorage', '0006_originalimage_alter_imagethumbnail_original_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imagethumbnail',
            index=models.Index(fields=['uuid'], name='image_thumbnail_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='originalimage',
            index=models.Index(fields=['uuid'], name='original_image_uuid_idx'),
        ),
    ]
